version: "3.1"
services: 
    mymongo: 
        image: "mongo"

    bkr_website:
        build: .
        ports: 
            - "5442:5442"
        environment: 
            - SERVER_PORT=5442
            - OPENVIDU_URL=https://192.168.1.16:4443
            - OPENVIDU_SECRET=BaatKarteRaho
            - IS_LOCAL=1